services:
  database_pgvector:
    image: pgvector/pgvector:pg16
    container_name: database_pgvector
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}"]
      interval: 5s
      timeout: 5s
      retries: 5

  embedding_service:
    build: ./Embedding_Service
    container_name: embedding_service
    ports:
      - "8001:8001"
    volumes:
      - hf_cache:/root/.cache/huggingface

  doc_upload_service:
    build: ./Document_Upload_Service
    container_name: doc_upload_service
    ports:
      - "8002:8002"
    environment:
      DB_HOST: database_pgvector
      DB_PORT: 5432
      DB_NAME: ${POSTGRES_DB}
      DB_USER: ${POSTGRES_USER}
      DB_PASSWORD: ${POSTGRES_PASSWORD}
      EMBEDDING_SERVICE_URL: http://embedding_service:8001/embed
      PDF_DIR: /app/Raw_Content
    volumes:
      - ./Document_Upload_Service/Raw_Content:/app/Raw_Content
    depends_on:
      database_pgvector:
        condition: service_healthy
      embedding_service:
        condition: service_started

  db_api:
    build: ./Database_Service
    container_name: database_api
    ports:
      - "8000:8000"
    environment:
      DB_HOST: database_pgvector
      DB_NAME: ${POSTGRES_DB}
      DB_USER: ${POSTGRES_USER}
      DB_PASS: ${POSTGRES_PASSWORD}
      DB_PORT: 5432
    depends_on:
      database_pgvector:
        condition: service_healthy

  graph_service:
    build: ./Graph_Service
    container_name: graph_service
    ports:
      - "8003:8003"
    environment:
      DATABASE_SERVICE_URL: http://database_api:8000
      GOOGLE_CLOUD_PROJECT: ${GOOGLE_CLOUD_PROJECT}
      GOOGLE_CLOUD_LOCATION: ${GOOGLE_CLOUD_LOCATION}
      GOOGLE_APPLICATION_CREDENTIALS: ${GOOGLE_APPLICATION_CREDENTIALS}
    volumes:
      - ./Graph_Service:/app
    depends_on:
      db_api:
        condition: service_started

volumes:
  postgres_data:
  hf_cache: